### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-search-relevance#146]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
You have the `search-relevance-dashboards-team` with 4 members that has maintain access to this repo. Only folks listed in MAINTAINERS/CODEOWNERS need to have maintain access, and groups don't support external collaborators and therefore should be removed. Please work with an admin to remove the group, and add individuals.

**Comment by macohen** [comment]
@dblock are you able to remove the group and add the individuals listed in CODEOWNERS?

**Comment by peternied** [comment]
@macohen Done!

**Comment by peternied** [comment]
Can you see the access settings on repo? Here is a screen shot - I believe this should be enough verification.  Pinging the admin team if there was something surprising would be a good way to deal with lack of access issues.

![image](https://user-images.githubusercontent.com/2754967/225711830-c88f02bf-44fd-4906-a11d-3fab183808c0.png)

**Comment by macohen** [comment]
@peternied I don't see the access settings on the repo.

**Comment by bbarani** [comment]
@msfroh @macohen Let me help you here.

**Comment by bbarani** [comment]
I checked the current access and everything looks good and baselined so closing this issue.

**Comment by macohen** [comment]
Reopening since I still do not see the "Manage access" screen that @peternied mentioned. Here's what I see when clicking "Settings."
<img width="1047" alt="Screenshot 2023-04-10 at 4 47 39 PM" src="https://user-images.githubusercontent.com/254449/230995783-5d54cd7a-659e-42d8-81ab-e3f8d5b34c1c.png">

**Comment by macohen** [comment]
Misunderstood that org admins still must be the ones to grant maintainer roles. It's not the repo owner.

**Comment by dblock** [comment]
Verified, thanks.
