### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/dashboards-search-relevance#152]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Dashboards Search Relevance repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Dashboards Search Relevance | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Certificate or Origin, Changelog Verifier, Lint Checker | https://github.com/opensearch-project/dashboards-search-relevance/issues/152 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by macohen** [comment]
We have informally said that coverage should not drop below 80%. We also have this .codecov.yml file which may not be working right: https://github.com/opensearch-project/dashboards-search-relevance/blob/main/.github/.codecov.yml. 

-[] Check CodeCov Configuration for Threshholds.

**Comment by scrawfor99** [comment]
Hi @macohen, thank you for the info, I will update that in the notes for the discussion. I appreciate you taking the time to follow up.

**Comment by macohen** [comment]
that codecov.yml file is in the right place now. closing this issue.
