### ISSUE TITLE
Make integ tests more defensive against dangling sample data

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/dashboards-search-relevance#159]
During the 2.6.0 release, the Cypress tests for this repo (running from https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/cypress/integration/plugins/search-relevance-dashboards/1_query_compare.spec.js) failed because it was unable to create sample data (in the `before()` step), because the sample data had been created but not cleaned up by another test.

We should defend against other tests' bad behavior so that our tests don't break.

I think https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/cypress/integration/plugins/custom-import-map-dashboards/import_vector_map_tab.spec.js#L14-L15 may be a model that we can copy -- delete all indices before trying to add sample data to start with a clean slate.

**Comment by sejli** [comment]
Closing, added in [#583](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/583).
