### ISSUE TITLE
[FEATURE] Add Windows Support

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/dashboards-search-relevance#16]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [x] Passing CI on Windows
- [ ] Documentation

**Comment by macohen** [comment]
Build failed on Windows. Added the following to the workflow, but it still failed. 
```
- name: Check LongPathsEnabled
  if: ${{ matrix.os == 'windows-latest' }}
  run: |
     (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
```

**Comment by macohen** [comment]
One more question, this is an experimental feature in 2.4. Given that, must it work on Windows?

**Comment by bbarani** [comment]
@macohen expectation is that any plugin on-boarded to 2.4.0 release should have working Windows CI on their repo to support that distribution going forward.

**Comment by dblock** [comment]
@macohen Are integration/cypress tests running on Windows, and/or are there any coverage differences between Linux and Windows tests? If yes, please reopen this issue until that gap is covered.

**Comment by msfroh** [comment]
Looks like the integration tests are only running on Ubuntu for now: https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/workflows/search-relevance-release-e2e-workflow.yml#L9

**Comment by msfroh** [comment]
(All of the other e2e testing workflows in opensearch-dashboards-functional-test test seem to use ubuntu-latest as well, though.)

**Comment by macohen** [comment]
builds pass CI for windows. we've been entirely focused on integ tests at this point. @bbarani What documentation are you looking for on this? Are there any examples?

**Comment by macohen** [comment]
Windows CI is passing. Closing issue.
