### ISSUE TITLE
Add dashboards-search-relevance plugin to source code page

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/dashboards-search-relevance#165]
Add dashboards-search-relevance plugin to source code page: https://opensearch.org/source.html#

**Comment by macohen** [comment]
Good point. I don't know if experimental plugins get added to that page though. @macrakis?

**Comment by macohen** [comment]
I also created a PR for DEVELOPER_GUIDE.md: #268 that is referenced in a link in #1948

**Comment by noCharger** [comment]
https://github.com/opensearch-project/project-website/pull/1948 merged, resolve issue
