### ISSUE TITLE
[PROPOSAL] Adding Sean Li and Louis Chu as Maintainers

### ISSUE THREAD

**Issue by macohen** [opensearch-project/dashboards-search-relevance#171]
The existing maintainers have voted and approved adding Sean Li (sejli) and Louis Chu (noCharger) as maintainers on this repo. Can you please add them to the maintainers list, @opensearch-project/admin?

**Comment by dblock** [comment]
@macohen PR a change into MAINTAINERS/CODEOWNERS and don't merge until that's done

**Comment by sejli** [comment]
Closing since the maintainers have been added. Thanks!
