### ISSUE TITLE
[Good first issue] Update message shown when a single index is selected in search comparison tool

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/dashboards-search-relevance#173]
### What is the bug?
When the search button is pressed and a single search is performed, an error message appears saying "An index is required. Select an index."

<img width="1570" alt="Screen Shot 2023-04-13 at 8 31 07 AM" src="https://user-images.githubusercontent.com/44716267/231810584-8c7ce022-e713-43e7-8948-c3f81a53b718.png">

### How can one reproduce the bug?
1. Select index on either left or right hand side
2. Click search button

### What is the expected behavior?
Three possibilities:
1. If a single search is not permitted, display an error message but do not execute the search.
2. If a single search is permitted, delete the error message.
3. If a single search is permitted, change the font color to black and display a recommendation wording such as "try comparing search results by selecting an index."

### Do you have any additional context?
I would want to clarify the expected behavior.

**Comment by noCharger** [comment]
@kgcreative @lauralexis would appreciate input on this. Thanks!

**Comment by lauralexis** [comment]
A single search is permitted. A single search can be executed on either sides (query 1 or query 2). I don't think the error message is necessarily a bug, because it explains why the search wasn't executed. We could adjust the error message for both sides for more clarity to say "An index is required to compare search results. Select an index." Let me know what you think.

**Comment by macohen** [comment]
I'd like to keep this as simple as we can right now. I think making the messaging clearer can work just fine, but if someone is willing to pick up @msfroh's suggestion later and that works for the UX then we could do that as well.

IMO, updating the text can work to be clearer. If we go down that path, we should also label this "good first issue."

**Comment by noCharger** [comment]
Thanks all for the great suggestions! To summarize, the next step in resolving this problem is to modify the error message. If someone wants to tweak the UX of this to auto-fill the index, please open a new issue.

**Comment by evankielley** [comment]
Will this issue be fixed by #267? If not, I can make a PR for this

**Comment by noCharger** [comment]
> Will this issue be fixed by #267? If not, I can make a PR for this

Nope it's an seperate issue. Please feel free to take it!
