### ISSUE TITLE
[FEATURE] Display pictures in search comparison tool for playground

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/dashboards-search-relevance#195]
### Is your feature request related to a problem?
Current comparison tool only display text document, which is not very intuitive comparing search results. We propose to display pictures when a url is available.

### What solution would you like?
See attachment for a mock up 
![search_comparison](https://user-images.githubusercontent.com/51798415/234626112-88b7b013-024f-469d-a600-102f2a2d9240.gif)

### What alternatives have you considered?
We could use greasemonkey script on client side to do the job, but it's not as easy.

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by sejli** [comment]
Hi @sean-zheng-amazon, do you have a link to the GreaseMonkey script that you are referring to?

**Comment by sejli** [comment]
Had some more questions needed for clarification:
* How does the tool know when to display an image? Will the field name always be `image` if there is an image to display?
* If not, will the tool need to parse through every link to determine whether or not it is an image?

**Comment by noCharger** [comment]
> Had some more questions needed for clarification:
> 
> * How does the tool know when to display an image? Will the field name always be `image` if there is an image to display?
> * If not, will the tool need to parse through every link to determine whether or not it is an image?

Looks like these decisions should be included in a low level design. It's fine to make implicit assumptions when prototyping. But, for the feature issue, can you elaborate on alternatives and trade-offs? Thanks.

**Comment by macohen** [comment]
closing this as complete; images will be moved to the main plugin in #286
