### ISSUE TITLE
[FEATURE] Show non-source fields in search comparison tool

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/dashboards-search-relevance#201]
### Is your feature request related to a problem?
Currently, the comparison tool only shows document source. Sometimes, though, I don't want to retrieve the whole document source because I have large text fields and vector fields. Also, sometimes I want to retrieve fields that are not available in source, but are available as doc values, stored fields, or are computed by a script.

### What solution would you like?
The results shown in the comparison tool should include fields from the `fields` property of each document. I would suggest that the result object first be populated with fields from the source (if available), then overlay the field values from the `fields` property -- if a field is available in both source and `fields`, the value in `fields` should overwrite the value in source.

### What alternatives have you considered?
We can limit the set of fields returned using the `_source` parameter in the search request, but that doesn't cover the cases where a field is not available in the source (but may be in doc values, a stored field, or be computed with `script_fields`). 

### Do you have any additional context?
No

**Comment by nung22** [comment]
@sejli I'd like to pick up this issue

**Comment by nung22** [comment]
Hi @msfroh I implemented a possible solution to this in #340: I wanted to see if this is what you were envisioning. Currently I'm only able to access `fields` by running a script on the OSD sample data sets. Are there any other properties you might want to access here?
