### ISSUE TITLE
Ensure working and passing CI.

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/dashboards-search-relevance#221]
A couple of CI failed needs investigation: 

https://github.com/opensearch-project/dashboards-search-relevance/issues/204#issuecomment-1569113607

In order to provide information on where the Cypress test failed on the browser, I'm wondering whether we can add video uploading as a cypress test option.

**Comment by noCharger** [comment]
Let's run the test suite on functional repo

**Comment by macohen** [comment]
Related to https://github.com/opensearch-project/search-processor/issues/162. 

We took a dependency on a backend plugin because it's faster than building OpenSearch itself. Most frontend plugins have a corresponding backend plugin, but this one does not.

**Comment by sejli** [comment]
The dependency on a backend plugin has been reverted back from `anomaly-detection` to `search-processor`. CIs no longer failing, closing issue.
