### ISSUE TITLE
(OUI Next Theme) Search Relevance

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/dashboards-search-relevance#257]
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

- [x] #306 

![Screen Shot 2023-07-27 at 12 19 28 PM](https://github.com/opensearch-project/oui/assets/105819041/6142b876-e826-4f83-9da8-e70acdc0cdcc)

- [x] #307 
- [x] #308

**Comment by macohen** [comment]
We'll need to push this change to 2.11.

**Comment by joshuarrrr** [comment]
OpenSearch Dashboards provides a theme-aware customization of the `textmate` theme for ace editor. See https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4609

Setting the theme to `textmate` is likely sufficient to fix the query editor appearance.

**Comment by joshuarrrr** [comment]
@macohen If your team would like a helping hand on resolving these, feel free to sign up for OpenSearch Dashboards developer office hours: https://opensearch.org/events/2023-0921-dev-officehours-dashboards/

**Comment by nung22** [comment]
@sejli Can I get assigned to this issue?

**Comment by nung22** [comment]
Hi @KrooshalUX, I'm currently tackling this issue and was wondering if you could elaborate on this point further "Empty state should utilize `EuiEmptyPrompt`." Just trying to get a better idea of what type of problem it is.

**Comment by joshuarrrr** [comment]
@nung22 Thanks for picking this up! Kroosh is out of the office for a while so @kgcreative or I should be able to help anser any of these questions. For the third item, the idea is to use standard layout components, which already are styled consistently.

From the screenshot, I believe this is the component to update:

https://github.com/opensearch-project/dashboards-search-relevance/blob/6fb31c89a298520bad0eadeac88939001d5aea32/public/components/query_compare/search_result/result_components/result_components.tsx#L21-L36

Here's the documentation and usage guide for EuiEmptyPrompt (note that, for semver reasons, the docs us the `OUI` namespace while we still use the `EUI` namespace in code): https://oui.opensearch.org/1.3/#/display/empty-prompt

**Comment by kgcreative** [comment]
@nung22 -- once you have something working on your local env, feel free to add a screenshot here and tag me, and I can give you quick validation from the UX side as to whether it looks right or not. If you're able to spin up an end-point to show WIP even better, but that can sometimes be extra time consuming for a small change like this.

**Comment by nung22** [comment]
@kgcreative This is what I have so far!

# Screenshots

### Before

Dark Mode

![Screenshot 2023-10-07 115045](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/f23be7a1-ebdd-4de9-aa0f-36385442a4cc)

Light Mode

![Screenshot 2023-10-07 115023](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/668c3617-beba-4b04-88b6-9d7addfd1a71)

### After

Dark Mode

![Screenshot 2023-10-07 114624](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/f6da3405-3f4b-4d70-b051-2cb0ac94817b)

Light Mode

![Screenshot 2023-10-07 114807](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/146fb03f-8eff-4528-9138-12d32010e8ec)


### Navigation to "Add Sample Data" page:

Dark Mode

![euiEmptyPrompt-darkMode](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/c49af993-413e-4e44-adbe-ec4f4a9af701)

Light Mode

![euiEmptyPrompt-lightMode](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/b65c28a5-7254-47fd-81f3-c6e35cbb844e)

**Comment by kgcreative** [comment]
> @kgcreative This is what I have so far!

Thanks so much!
For this empty prompt, let's not link to adding sample data. Instead, let's use empty prompt, and supress the primary action.

![image](https://github.com/opensearch-project/dashboards-search-relevance/assets/3443142/c9baf56f-2513-42a8-89ee-910853fdf9c1)
```
  iconType="search"
  title={<h2>No results</h2>}
  body={
      <Fragment>
        <p>
          Add at least one query to display search results.
        </p>
      </Fragment>
    }
```

**Comment by kgcreative** [comment]
Similarly, when only one query is present, 

![image](https://github.com/opensearch-project/dashboards-search-relevance/assets/3443142/ab8cb90c-a644-41a0-aad2-18c7fed999f2)

Let's update the body of the empty pane to:
```
iconType="search"
  title={<h2>No results</h2>}
  body={
      <Fragment>
        <p>
          Add a second query to display search comparison results.
        </p>
      </Fragment>
    }
```

**Comment by nung22** [comment]
> > @kgcreative This is what I have so far!
> 
> Thanks so much! For this empty prompt, let's not link to adding sample data. Instead, let's use empty prompt, and supress the primary action.
> 
> ![image](https://user-images.githubusercontent.com/3443142/274025632-c9baf56f-2513-42a8-89ee-910853fdf9c1.png)
> 
> ```
>   iconType="search"
>   title={<h2>No results</h2>}
>   body={
>       <Fragment>
>         <p>
>           Add at least one query to display search results.
>         </p>
>       </Fragment>
>     }
> ```

Appreciate the guidance! Is this what you meant?

**Comment by nung22** [comment]
> Similarly, when only one query is present,
> 
> ![image](https://user-images.githubusercontent.com/3443142/274027670-ab8cb90c-a644-41a0-aad2-18c7fed999f2.png)
> 
> Let's update the body of the empty pane to:
> 
> ```
>   iconType="search"
>   title={<h2>No results</h2>}
>   body={
>       <Fragment>
>         <p>
>           Add a second query to display search comparison results.
>         </p>
>       </Fragment>
>     }
> ```

With only one query present:

![Screenshot 2023-10-10 140518](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/e5c53804-a281-4e7f-a854-446166a82e06)

![Screenshot 2023-10-10 140611](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/e3febfac-3856-4e91-8560-60f0fb2ce032)

**Comment by kgcreative** [comment]
@nung22 LGTM!

@joshuarrrr over to you for code review

**Comment by noCharger** [comment]
Close this issue after all tasks complete
