### ISSUE TITLE
[FEATURE] Add Ability to Select a Search Pipeline in Comparison Tool

### ISSUE THREAD

**Issue by macohen** [opensearch-project/dashboards-search-relevance#260]
### Is your feature request related to a problem?
With the launch of search pipelines, we want users to be able to select a pipeline for two reasons: 1) ease of use/clarity, 2) certain processors cannot be used in an ad-hoc search pipeline because the initialization is too costly, especially when connecting to external services.

### What solution would you like?
A user of search pipelines should be able to compare two different queries using the same or different search pipelines. We also should consider a solution that makes room for search configurations. Think of a search configuration as a unit containing anything  that you would want to compare to another search configuration for manual comparison or A/B testing. This would include queries, ML models, search pipelines, processor configurations, analyzers, etc. In this case we really want to include only search pipelines. 

### What alternatives have you considered?
Comparing two different sets of results with different pipelines is possible using two Dev Tools windows or two curl commands. These are not as user friendly. 

### Do you have any additional context?
There is a prototype available here for search pipeline selection: https://ml.playground.opensearch.org/app/searchRelevance#/

**Comment by macohen** [comment]
@kgcreative thinking about just adding the search pipeline selector to the tool, but there may be a better way to grow into search configurations... Thoughts?

**Comment by kgcreative** [comment]
![image](https://github.com/opensearch-project/dashboards-search-relevance/assets/3443142/d78c64cd-407f-4903-8727-d151dbca401c)

@macohen -- Makes sense to me! I've included a quick mock of what the pipeline selection tool should look like

**Comment by nung22** [comment]
@sejli Can I pick this up?
