### ISSUE TITLE
[FEATURE] [Search Comparison Tool] Expand Document Source

### ISSUE THREAD

**Issue by sejli** [opensearch-project/dashboards-search-relevance#285]
### Is your feature request related to a problem?
Document sources in the search results of the search comparison tool are truncated to `95px`. In the tool, there is currently no way to view the entire document source, if the source contains lines would overfill the row.
![image](https://github.com/opensearch-project/dashboards-search-relevance/assets/47805161/b63d7379-78a5-4dbf-9b3a-880053eaec19)

### What solution would you like?
We want users to be able to expand the row to view the entire document source. Document viewers, like [Discover](https://playground.opensearch.org/app/discover#) or [Log Explorer](https://playground.opensearch.org/app/observability-logs#/explorer/H7MDiokB18GS7609H0Q5), should have the option to show a more detailed view of a document's source.

### What alternatives have you considered?
The only other way to view the document source is to visit DevTools and run the same query. However, this eliminates the possibility of having a side by side comparison with rankings.

### Do you have any additional context?
As mentioned previously, [Discover](https://playground.opensearch.org/app/discover#) or [Log Explorer](https://playground.opensearch.org/app/observability-logs#/explorer/H7MDiokB18GS7609H0Q5) are ideas for starting points.

**Comment by nung22** [comment]
Can I pick this up @sejli?

**Comment by nung22** [comment]
Hi @kgcreative, I was working on an implementation of this with the `OuiPopover` component and was hoping to get your thoughts on it so far.

# Screenshots

### Source details closed
![issue-285-pic1](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/d06d83a2-fb38-4fcb-9bf6-fdda869d1513)

### Source details open
![issue-285-pic2](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/f73a59cf-9f37-40db-98fc-b95ede8236a6)

### In action
![issue-285-gif](https://github.com/opensearch-project/dashboards-search-relevance/assets/37952714/5e2aea40-d858-4937-b984-14d6d9c5953a)

**Comment by kgcreative** [comment]
@sejli - this looks good to me
