### ISSUE TITLE
[FEATURE] Support Multiple Data Source in Search Relevance Dashboards Plugin

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/dashboards-search-relevance#371]
### Is your feature request related to a problem?
With multiple data source enabled, users of OpenSearch Dashboards are able to create data source connections and query local and remote OpenSearch clusters. Enabling multiple data source at dashboards plugin would ensure users that have been using the multiple data source feature to have a consistent experience in the dashboard, and allows users to use the same dashboard for different clusters.

### What solution would you like?
Support multiple data source in the search relevance dashboards plugin and allow user to use one dashboard for different backend clusters

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by msfroh** [comment]
@sejli -- Are you able to take this one?

**Comment by sejli** [comment]
@sumukhswamy will be picking this up. I'll assign him to this issue.
