### ISSUE TITLE
[FEATURE] Navigate to Import Sample Data Page without Refresh when New Home is Enabled

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/dashboards-search-relevance#456]
### Is your feature request related to a problem?
When the new home page and workspace are enabled, there is no direct navigation to the import sample data page without causing a page refresh.

### What solution would you like?
1. Modify the `CreateIndex` component to check if the new home page and workspace are enabled.
2. Add an `onClick` handler to the "Add Sample Data" link when the new home page and workspace are enabled.
3. In the `onClick` handler, call `application.navigateToApp` with `import_sample_data` to navigate to the import sample data page.
4. Ensure that the navigation happens without causing a page refresh.

### What alternatives have you considered?
N/A

### Do you have any additional context?
N/A

**Comment by andrross** [comment]
Resolved by #457
