### ISSUE TITLE
[FEATURE] Run integration tests as part of the OpenSearch-Dashboards distribution

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/dashboards-search-relevance#8]
**Is your feature request related to a problem?**
Following a problem in another plugin (https://github.com/opensearch-project/opensearch-build/issues/2043), and coming from https://github.com/opensearch-project/opensearch-build/issues/58, there's no automated testing that this plugin runs as part of the OpenSearch distribution.

**What solution would you like?**
Run integration tests as part of the distribution.

A bit different from the OpenSearch Gradle IntegTest, the cypress test on dashboards need to be added to https://github.com/opensearch-project/opensearch-dashboards-functional-test

**Comment by macohen** [comment]
@mingkunm are you able to work on this? do you need any assistance?

**Comment by msfroh** [comment]
Fixed by https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/362
